export interface LeaveDataApprove {
  leaveID: number;
  leaveArchive: string;
  empID: number | null;
  cateID: number | null;
  time_Start: string | null;
  time_End: string | null;
  dateLeave: string | null;
  leaveDay: number | null;
  approved: number | null;
  time_Applied: string | null;
  timeLine: string;
  comment: string;
  commentLeave: string;
  leavePlus: boolean | null;
  leaveArrange: boolean | null;
  userID: number | null;
  approvedBy: number | null;
  editRequest: number | null;
  status_Line: boolean | null;
  created: string | null;
  updated: string | null;
  status_Lock: boolean | null;
  lock_Leave: boolean | null;
  mailContent_Lock: string;
  commentArchive: string;
  empName: string;
  empNumber: string;
  deptIDName: string;
  deptNameLangZH: string;
  deptNameLangEN: string;
  deptNameLangVN: string;
  partName: string;
  partCode: string;
  category: string;
  categoryLangZH: string;
  categoryLangVN: string;
  categoryLangEN: string;
  dateStart: string;
  dateStartOrder: string | null;
  dateEnd: string;
  status: string;
  timeStart: string;
  timeEnd: string;
  createdString: string;
  leaveDayString: string;
  leaveHourString: string;
  searchDate: string;
  pnc: string;
  updatedString: string;

  //check Accept
  accept: Boolean;
  isMarker: boolean;
}
